import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { 
  ClipboardList, Copy, FileText, Lightbulb, 
  Upload, Image, Palette, Globe, Sparkles
} from "lucide-react";

type InitiativeType = "website" | "web-app" | "mobile-app" | "saas" | "ai-tool" | "ecommerce";

const initiativeTypes: { value: InitiativeType; label: string; description: string }[] = [
  { value: "website", label: "Website", description: "Marketing or informational site" },
  { value: "web-app", label: "Web Application", description: "Interactive browser-based tool" },
  { value: "mobile-app", label: "Mobile App", description: "iOS or Android application" },
  { value: "saas", label: "SaaS Platform", description: "Subscription-based service" },
  { value: "ai-tool", label: "AI Tool", description: "AI-powered solution" },
  { value: "ecommerce", label: "E-commerce", description: "Online store or marketplace" },
];

const PlannerContent = () => {
  const [initiativeType, setInitiativeType] = useState<InitiativeType>("website");
  const [clientName, setClientName] = useState("");
  const [brief, setBrief] = useState("");
  const [generatedPrompt, setGeneratedPrompt] = useState("");

  const generatePrompt = () => {
    if (!clientName || !brief) {
      toast.error("Client name and brief are required");
      return;
    }

    const typeInfo = initiativeTypes.find(t => t.value === initiativeType);
    
    const prompt = `# Initiative Planning Document

## Client
${clientName}

## Initiative Type
${typeInfo?.label} - ${typeInfo?.description}

## Directive
${brief}

## Planning Framework

### 1. Discovery Phase
- Stakeholder interviews
- Competitive analysis
- User research
- Technical audit (if applicable)

### 2. Strategy Phase
- Goals and success metrics
- User personas
- Journey mapping
- Feature prioritization

### 3. Design Phase
- Brand alignment
- Information architecture
- Wireframes and prototypes
- Visual design system

### 4. Implementation Phase
- Technical architecture
- Development sprints
- Quality assurance
- Security review

### 5. Launch Phase
- Deployment strategy
- Monitoring setup
- Documentation
- Training materials

### 6. Growth Phase
- Analytics implementation
- Optimization opportunities
- Maintenance schedule
- Expansion roadmap

---

*Generated by SMAIT Intelligence Layer*
*Ready for operator dispatch*`;

    setGeneratedPrompt(prompt);
    toast.success("Initiative plan generated");
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedPrompt);
    toast.success("Copied to clipboard");
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Input Section */}
        <Card className="bg-card/50 backdrop-blur-sm border-white/10">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ClipboardList className="h-5 w-5 text-primary" />
              Initiative Planner
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label>Initiative Type</Label>
              <Select value={initiativeType} onValueChange={(v) => setInitiativeType(v as InitiativeType)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {initiativeTypes.map(type => (
                    <SelectItem key={type.value} value={type.value}>
                      <div>
                        <span className="font-medium">{type.label}</span>
                        <span className="text-muted-foreground ml-2 text-xs">{type.description}</span>
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Client / Organization</Label>
              <Input
                placeholder="Enter client or organization name"
                value={clientName}
                onChange={(e) => setClientName(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label>Brief / Directive</Label>
              <Textarea
                placeholder="Describe the initiative objectives, constraints, and desired outcomes..."
                value={brief}
                onChange={(e) => setBrief(e.target.value)}
                className="min-h-[150px] resize-none"
              />
            </div>

            <Button onClick={generatePrompt} className="w-full gap-2">
              <Sparkles className="h-4 w-4" />
              Generate Plan
            </Button>
          </CardContent>
        </Card>

        {/* Output Section */}
        <Card className="bg-card/50 backdrop-blur-sm border-white/10">
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              <span className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-primary" />
                Generated Plan
              </span>
              {generatedPrompt && (
                <Button size="sm" variant="outline" onClick={copyToClipboard} className="gap-1">
                  <Copy className="h-3 w-3" />
                  Copy
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {generatedPrompt ? (
              <div className="p-4 rounded-lg bg-black/30 border border-white/10 max-h-[400px] overflow-y-auto">
                <pre className="text-sm text-muted-foreground whitespace-pre-wrap font-mono">
                  {generatedPrompt}
                </pre>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-muted-foreground">
                <Lightbulb className="h-12 w-12 mb-3 opacity-50" />
                <p className="text-sm">Complete the form to generate an initiative plan</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default PlannerContent;
